language: ruby

rvm: 2.3.3

addons:
  apt:
    packages:
      - libqtwebkit-dev
  postgresql: "9.6"

services:
  - postgresql
  # We don't start elasticsearch here; instead we download it later and run it
  # directly in order to enable the test cluster to start up. See
  # https://github.com/elastic/elasticsearch-ruby/issues/365 .

cache:
  directories:
    - travis_phantomjs

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.4.tar.gz
  - tar -xvf elasticsearch-5.6.4.tar.gz

  # update phantomjs
  - |
      export PHANTOMJS_VERSION=2.1.1
      export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH
      if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then
        rm -rf $PWD/travis_phantomjs
        mkdir -p $PWD/travis_phantomjs
        wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
        tar -xvf phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs
      fi
      phantomjs -v

env:
  - TEST_CLUSTER_COMMAND=elasticsearch-5.6.4/bin/elasticsearch

before_script:
  - psql -c 'create database chill_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:load RAILS_ENV=test
  - mkdir -p tmp/cache

script:
  - bundle exec rspec spec/
